#!/home/yaya/.pyenv/plugins/python
import psycopg2

con = psycopg2.connect(database='game',user='zhao',password='12345678',host='127.0.0.1',port='5432')

# print(con)
cor = con.cursor()

values = []
for i in range(1,10):
    value = "(%d, 'team_%d', %d, 'leader_%d', %d, %d, 1, '', 'dajiakaixin', 'henkaixin' ,1, '', False)"%(i,i,1000+i,i,30+i,20+i)
    values.append(value)
sql = "insert into team (id,team_name,leader_id,leader_name,count_total,count,status,verify_time,comment,check_comment,comment_status,apply_message,is_delete) values "
for value in values:
    sql += value 
    
print(sql)
