#!/home/yaya/.pyenv/plugins/python 


import subprocess

obj = subprocess.Popen(["python"],shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)

stdout,stderr = obj.communicate()
print(stdout,stderr)

if obj.returncode == 0 :
    print(obj.returncode,obj.stderr)
else:
    print(obj.returncode,obj.stdout)
    obj.stdin.write('print(1)\n'.encode('utf-8'))
    obj.stdin.write('print(2)\n'.encode('utf-8'))
    obj.stdin.write('print(3)\n'.encode('utf-8'))
    obj.stdin.write('print(4)\n'.encode('utf-8'))
    out_error_list = obj.communicate()
    print(out_error_list)
